### ISSUE TITLE
 Resource not accessible by integration

### ISSUE THREAD

**Issue by ablil** [AleksandrFurmenkovOfficial/ai-code-review#3]
I've copied the exact snippet on the README and added to a repo, after raising a PR the github action fails to run with the error:

```
 Resource not accessible by integration
```

Sidenote: I only added OPENAI secret key to the repo, as I believe the other keys are handled by Github.

**Comment by AleksandrFurmenkovOfficial** [comment]
@ablil Just tested with a closed repo on a different account, and everything is fine.
"Resource not accessible by integration" is a permissions-related issue in your repository. Please check https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ for details, your GITHUB_TOKEN should have permissions to read PR content and write comments.
