### ISSUE TITLE
returning 429

### ISSUE THREAD

**Issue by millionacrenest** [AleksandrFurmenkovOfficial/ai-code-review#4]
Every time I open a pull request, ai-code-review returns a 429. I allowed several days between attempts but received the same response.

![Screenshot 2023-05-30 at 1 03 14 PM](https://github.com/AleksandrFurmenkovOfficial/ai-code-review/assets/4943621/dffee635-5276-430e-a0cb-a4f1a15cb1ac)

**Comment by AleksandrFurmenkovOfficial** [comment]
Sometimes the OpenAI server may reject a request due to a temporary overload. I add a retry to deal with this.
